---
driver:
  name: vagrant
  synced_folders:
    - [".", "/vagrant"]


provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[sfdc-aem::author]
    attributes: