name             'cyly-aem'
maintainer       'DigitalLync, Inc.'
maintainer_email 'shashi@cyber-lync.com'
license          'All rights reserved'
description      'Installs/Configures cyly-aem'
long_description 'Installs/Configures cyly-aem'
version          '0.9.90'

depends 'aem', '~> 1.1.15'
depends 'sudo', '~> 2.7.1'
depends 'ssh_authorized_keys', '~> 0.1.0'
depends 'apache2', '~> 3.0.0'
depends 'ulimit', '~> 0.3.3'
depends 'sysctl', '~> 0.6.2'
depends 'java'